#ifndef ENGINE_ENGINE_SHARED_WEAPON_TYPES_H
#define ENGINE_ENGINE_SHARED_WEAPON_TYPES_H
#undef ENGINE_ENGINE_SHARED_WEAPON_TYPES_H // this file will be included several times

enum
{
	INFWEAPON_NONE,
	INFWEAPON_HAMMER,
	INFWEAPON_GUN,
	INFWEAPON_SHOTGUN,
	INFWEAPON_GRENADE,
	INFWEAPON_RIFLE,
	INFWEAPON_NINJA,
	
	INFWEAPON_ENGINEER_RIFLE,
	
	INFWEAPON_SNIPER_RIFLE,
	
	INFWEAPON_SOLDIER_GRENADE,
	
	INFWEAPON_SCIENTIST_GRENADE,
	INFWEAPON_SCIENTIST_RIFLE,
	
	INFWEAPON_MEDIC_GRENADE,
	INFWEAPON_MEDIC_RIFLE,
	INFWEAPON_MEDIC_SHOTGUN,
	
	INFWEAPON_HERO_GRENADE,
	INFWEAPON_HERO_RIFLE,
	INFWEAPON_HERO_SHOTGUN,
	
	INFWEAPON_BIOLOGIST_SHOTGUN,
	INFWEAPON_BIOLOGIST_RIFLE,
	
	INFWEAPON_LOOPER_RIFLE,
	INFWEAPON_LOOPER_GRENADE,
	
	INFWEAPON_NINJA_HAMMER,
	INFWEAPON_NINJA_GRENADE,
	
	INFWEAPON_MERCENARY_GUN,
	INFWEAPON_MERCENARY_GRENADE,
	
	NB_INFWEAPON
};

enum
{
	INFAMMO_LASER,
	INFAMMO_PLASMA,
	
	NB_INFAMMO
};

#endif
